Controllers/HomeController.cs(39,29): error CS0246: The type or namespace name 'IndexViewModel' could not be found (are you missing a using directive or an assembly reference?) [/data/git/starsky/starsky/starsky/starsky.csproj]